name: 'With Docker'
description: 'Run a given stage with Docker Image'
inputs:
  container-name:
    description: 'Docker container name to use'
    type: string
    required: true
  tag-name:
    description: 'Docker image tag to use'
    type: string
    required: false
    default: russell-flow
  subdir:
    description: 'Subdirectory where code is cloned.'
    required: false
    type: string
    default: './'
  os:
    description: 'OS to setup Docker for.'
    required: false
    type: string
    default: 'ubuntu'
  distro:
    description: 'Distribution to setup Docker for.'
    required: false
    type: string
    default: 'noble'
  clang:
    description: 'clang version to use.'
    required: false
    type: number
    default: 20
  dockerfile:
    description: 'Hardcode the path of the dockerfile to use.'
    required: false
    type: string
    default: '.github/workflows/Dockerfile.russell'
runs:
  using: 'composite'
  steps:
  - name: 'Set up Docker'
    uses: nick-invision/retry@v3
    with:
      timeout_minutes: 30
      # Attempts are done because CI sometimes fail due to external reasons,
      # and instead of just failing, we may give building a docker image a second chance.
      max_attempts: 2
      retry_on: error
      command: |
        set -euxo pipefail

        CONTAINER_NAME=${{ inputs.container-name }}
        DOCKERFILE=${{ inputs.dockerfile }}
        CLANG_VERSION=${{ inputs.clang }}
        TAG_NAME=${{ inputs.tag-name }}

        RUSSELL_BRANCH=${{ github.head_ref || github.ref_name }}
        FLOW9_BRANCH=master
        WORKSPACE=${{ github.workspace }}
        USER=test-user
        GROUP=test-user

        docker build . --file ${DOCKERFILE}          \
          --tag ${TAG_NAME}                          \
          --build-arg USER="${USER}"                 \
          --build-arg GROUP="${GROUP}"               \
          --build-arg RUSSELL_BRANCH="${RUSSELL_BRANCH}"     \
          --build-arg FLOW9_BRANCH="${FLOW9_BRANCH}"     \

        docker run -d --name ${CONTAINER_NAME} \
          --user ${USER} \
          -v ${WORKSPACE}:/workspace \
          ${TAG_NAME} \
          tail -f /dev/null  # Keep container running

        # Give the container a moment to start
        sleep 2


